### ISSUE TITLE
Does not handle datapackage.json files with schema lookups

### ISSUE THREAD

**Issue by workergnome** [davbre/mira#4]
Was trying this with our schema from the Carnegie Museums of Pittsburgh [(datapackage.json)](https://github.com/cmoa/collection/blob/master/datapackage.json).  Unfortunately, it does not validate.

We have two different files that both use the same schema, so we are using the [schemas proprty](http://dataprotocols.org/data-packages/#schemas-property) to use a single schema definition for both files. 

However, when trying to upload the datapackage.json file, I get the following error:

```
Datapackage ["Resource 'schema' must be a Hash.", "Path: cmoa.csv.", "Resource 'schema' must be a Hash.", "Path: teenie.csv."]```

**Comment by davbre** [comment]
@workergnome - thanks for opening the issue. Yes, it doesn't currently deal with this scenario. When I get some time, I'll take a closer look.

**Comment by davbre** [comment]
I have made some updates and I am now able to upload your datapackage and import the two csv files into Mira. In order to do that I had to make some changes to your datapackage.json file. Some of these changes are in [this pull request](https://github.com/cmoa/collection/pull/11) I made to your repository. Some other changes I made are in [this commit](https://github.com/davbre/collection/commit/5968cd624aa281151a9dfa727f84ba3204e75d27) on my fork of your project. I'm guessing you'll not want to integrate them so did not make a pull request.

The additional changes I made were:
- I re-classified your "date" fields as "string", as they don't contain clean dates. For the purpose of importing the data into the database, this was necessary.
- To the "provenance_text" and "image_url" fields I added the following:
   "mira": { "index": false }

 This relates to [this issue](https://github.com/davbre/mira/issues/6).

**Comment by davbre** [comment]
With the latest commit of Mira I can now upload the two csv files (cmoa.csv and teenie.csv). The only change I needed to make was to add "mira": { "index": false } to the "provenance_text" and "image_url" fields in the datapackage.json file, as per my comment above.
